/**
 * API 错误码常量 — 对应 api.md §12.4 完整错误码清单。
 *
 * 用法：
 *   const result = await post('/auth/login', { ... })
 *   if (!result.ok) {
 *     if (result.error.code === ERRORS.ACCOUNT_BANNED) { ... }
 *   }
 */

export const ERRORS = {
  // ── Generic ──
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONTENT_TOO_LARGE: 'CONTENT_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',

  // ── Auth / Token ──
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  TOKEN_INVALID_OR_EXPIRED: 'TOKEN_INVALID_OR_EXPIRED',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  MISSING_OAUTH_PENDING: 'MISSING_OAUTH_PENDING',
  STEP_UP_REQUIRED: 'STEP_UP_REQUIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_MERGED: 'ACCOUNT_MERGED',
  ACCOUNT_PENDING_DELETION: 'ACCOUNT_PENDING_DELETION',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  BAD_STATE: 'BAD_STATE',
  OAUTH_ERROR: 'OAUTH_ERROR',
  OAUTH_PROVIDER_ERROR: 'OAUTH_PROVIDER_ERROR',
  PKCE_VERIFICATION_FAILED: 'PKCE_VERIFICATION_FAILED',

  // ── MFA ──
  INVALID_TOTP_CODE: 'INVALID_TOTP_CODE',
  TOTP_CODE_REPLAY: 'TOTP_CODE_REPLAY',
  TOTP_ALREADY_ENABLED: 'TOTP_ALREADY_ENABLED',
  TOTP_NOT_ENABLED: 'TOTP_NOT_ENABLED',
  MFA_CHALLENGE_EXHAUSTED: 'MFA_CHALLENGE_EXHAUSTED',

  // ── Passkey ──
  PASSKEY_VERIFICATION_FAILED: 'PASSKEY_VERIFICATION_FAILED',
  PASSKEY_ALREADY_REGISTERED: 'PASSKEY_ALREADY_REGISTERED',
  PASSKEY_NAME_TAKEN: 'PASSKEY_NAME_TAKEN',
  PASSKEY_REPLAY_DETECTED: 'PASSKEY_REPLAY_DETECTED',
  PASSKEY_FROZEN: 'PASSKEY_FROZEN',

  // ── Conflict / Resource ──
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  OAUTH_ALREADY_LINKED: 'OAUTH_ALREADY_LINKED',
  ALREADY_BOUND_TO_SELF: 'ALREADY_BOUND_TO_SELF',
  PROVIDER_ALREADY_BOUND: 'PROVIDER_ALREADY_BOUND',
  IDEMPOTENCY_KEY_MISMATCH: 'IDEMPOTENCY_KEY_MISMATCH',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  LAST_LOGIN_METHOD: 'LAST_LOGIN_METHOD',
  ALREADY_VOTED: 'ALREADY_VOTED',
  SELF_VOTE_FORBIDDEN: 'SELF_VOTE_FORBIDDEN',
  CONTRIBUTION_NOT_EDITABLE: 'CONTRIBUTION_NOT_EDITABLE',
  DUPLICATE_SUBMISSION: 'DUPLICATE_SUBMISSION',

  // ── Resources ──
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CONTRIBUTION_NOT_FOUND: 'CONTRIBUTION_NOT_FOUND',
  EDIT_REQUEST_NOT_FOUND: 'EDIT_REQUEST_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  PASSKEY_NOT_FOUND: 'PASSKEY_NOT_FOUND',
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND',
  OAUTH_NOT_BOUND: 'OAUTH_NOT_BOUND',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_IMAGE: 'INVALID_IMAGE',

  // ── Roles ──
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_GRANTED: 'ROLE_ALREADY_GRANTED',
} as const
